# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: 'Dynamic Programming'
  items: 
    - label: 'Elevator Rides'
      link: '/dynamic-programming/elevator-rides'
- label: 'Tree Algorithms'
  items:
    - label: 'Subordinates'
    link: '/tree-algorithms/subordinates'
    - label: 'Tree Matching'
    link: '/tree-algorithms/tree-matching'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/himanshuhsn/CSES
