# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: 'Dynamic Programming'
  items: 
    - label: 'Elevator Rides'
      link: '/dynamic-programming/elevator-rides'
- label: 'Tree Algorithms'
  items:
    - label: 'Subordinates'
    link: '/tree-algorithms/subordinates'
    - label: 'Tree Matching'
    link: '/tree-algorithms/tree-matching'
    - label: 'Tree Diameter'
    link: '/tree-algorithms/tree-diameter'
    -label: 'Tree Distances 1'
    link: '/tree-algorithms/tree-distances-1'
    -label: 'Tree Distances 2'
    link: '/tree-algorithms/tree-distances-2'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/himanshuhsn/CSES
