# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Dynamic Programming
  items: 
    - label: 'Elevator Rides'
      link: '/dynamic-programming/creating-docs'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/himanshuhsn/CSES
