name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Adjust to your Node.js version

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Gatsby Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BUILD_TRIGGER }}
          publish_dir: ./public # Change this to the build output directory of your Gatsby project
